### ISSUE TITLE
train_set.py is running indefinintely

### ISSUE THREAD

**Issue by dingusagar** [giulbia/baby_cry_detection#10]
train_set.py is running forever.

The log file generated is attached here.
 
There are  108 files in the directory ./data/902 - Noise. But according to the log file only 53 are getting processed. It gets hung on reading the 53rd ogg file.

2018-02-07 07:07:05 AM - INFO - Reading file: /home/dingu/PycharmProjects/baby_cry_detection/pc_main/../data/902 - Noise/5-156999-C.ogg ...

[logs_pc_methods_feat_eng.log](https://github.com/giulbia/baby_cry_detection/files/1701421/logs_pc_methods_feat_eng.log)

**Comment by dingusagar** [comment]
actually this problem occurs only for the Noise category. When I bypassed the Noise category, feature extraction ran successfully for all other categories - Crying baby , Silence and Baby laugh

**Comment by giulbia** [comment]
That's weird.

I thought about file type in _Noise_ folder, but it can't be the reason as it is the same kind of file you find in _Crying baby_ folder (_.ogg_). Moreover, from the log file, all the previous signals take reasonable time to be processed. Is it possible that only one file (5-156999-C.ogg) is corrupted somehow ?

**Comment by dingusagar** [comment]
You were right. Some 5 files in the Crying baby folder was corrupted. I removed them from the folder and ran it again. It worked. It generated the output numpy file also.
Thanks
