### ISSUE TITLE
help me to get accurate predictions with live data

### ISSUE THREAD

**Issue by cojangee** [giulbia/baby_cry_detection#22]
Good evening i had build the model using data of baby cry,laugh,noise ,
silence from data file
Finally i import this model to raspberry pi.
I got stuck when i am recoding live data from microphone here i am getting
wrong detection.
Example when i play baby cry its predicting zero
/// this is my microphone //
https://www.amazon.com/Microphone-Computer-Laptop-Desktop-Driver/dp/B078J9BTMF
Please help me to get accurate predictions with live data
Thanking you

**Comment by prashanthkolaneru** [comment]
@devilsun1 please use condenser microphone https://www.amazon.in/Powerpak-SF-922B-Condenser-Microphone-Reduction/dp/B074T988PW/ref=sr_1_1?keywords=SF-922B+Condenser+Microphone&qid=1565162524&s=gateway&sr=8-1

**Comment by devilsun1** [comment]
> @devilsun1 please use condenser microphone https://www.amazon.in/Powerpak-SF-922B-Condenser-Microphone-Reduction/dp/B074T988PW/ref=sr_1_1?keywords=SF-922B+Condenser+Microphone&qid=1565162524&s=gateway&sr=8-1

**Comment by cojangee** [comment]
> @devilsun1 please use condenser microphone https://www.amazon.in/Powerpak-SF-922B-Condenser-Microphone-Reduction/dp/B074T988PW/ref=sr_1_1?keywords=SF-922B+Condenser+Microphone&qid=1565162524&s=gateway&sr=8-1

thank you !! :) i will buy it
