### ISSUE TITLE
No such file or directory when saving training set

### ISSUE THREAD

**Issue by electron64** [giulbia/baby_cry_detection#7]
Hello i get this error when i run "test_model.py"
it was the same for train_set and train_model.
Any idea how to fix it, please?

python test_model.py
Traceback (most recent call last):
  File "test_model.py", line 105, in <module>
    main()
  File "test_model.py", line 98, in main
    with open(os.path.join(save_path, 'prediction.txt'), 'wb') as text_file:
IOError: [Errno 2] No such file or directory: '/root/baby_cry_detection/build/lib.linux-x86_64-2.7/pc_main/../../output/prediction/prediction.txt'

**Comment by electron64** [comment]
Hi, i solved the errors.
But on the raspberry (model 3) after i trained the model and i put the ".pkl" file and ".egg" file in the right folder on my raspberry  it  never recognizes the cry.
I listened what is recorded during the process. It sounds OK.
I've no errors on console but the prediction are always 0.

I tested on the Pc using using test_model.py and most of the prediction are ok.

Did i missed a step on the raspberry?
Is it matter if it is raspberry3 model?

Thank you in advance for your help.

**Comment by giulbia** [comment]
Hi,

I am glad to hear that you managed to deploy the whole project on your Raspberry Pi :)

I don't think there is a problem with your pi. How are you recording the cry? Is it an actual baby?

**Comment by electron64** [comment]
Hi, i fixed the problem, i reinstalled ffmeg and libvorbis, after that i tried with one sound used for the training via the 'make_prediction.py' on the pi. Prediction was OK.
So I tried with my daughter's voice in live.
Et voilà , It works!
Thank 's again for sharing that nice program!
Great work!

**Comment by raspberian1234** [comment]
Hi, i am working on same thing to detect cry. initially how to proceed with the open source. i am using raspberry pi 3 B and a USB microphone. Thanks in advance for your help.
