### ISSUE TITLE
makeprediction.py cant find proper arguments

### ISSUE THREAD

**Issue by dingusagar** [giulbia/baby_cry_detection#9]
in the makeprediction.py file

    parser = argparse.ArgumentParser()
    parser.add_argument('--load_path_data',
                        default='%s/../recording/' % os.path.dirname(os.path.abspath(__file__)))
    parser.add_argument('--load_path_model',
                        default='%s/../model/' % os.path.dirname(os.path.abspath(__file__)))
    parser.add_argument('--save_path',
                        default='%s/../prediction/' % os.path.dirname(os.path.abspath(__file__)))

These codes expect two folders model and prediction. But they are not there.  What should I do to get those folders with appropriate files.

**Comment by giulbia** [comment]
Hi,

Training the model is supposed to happen on your computer (not on RaspberryPi) so you need to train it by executing  pc_main/train_model.py.

**Comment by dingusagar** [comment]
I tried to run train_model.py
I am getting the following error


Traceback (most recent call last):
  File "train_model.py", line 70, in <module>
    main()
  File "train_model.py", line 45, in main
    X = np.load(os.path.join(load_path, 'dataset.npy'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: '/opt/baby_cry_detection/pc_main/../../output/dataset/dataset.npy'

**Comment by giulbia** [comment]
Sorry I didn't specify that you have to run _train_set.py_. This is because first you need to do the feature engineering and _train_set.py_ does exactly that. It then saves data as a numpy file (dataset.npy). 

Please note that at the top of the script _train_set.py_, you can set the folder where to save dataset.npy. Make sure that train_model.py reads dataset.npy from the same folder (you can set it at the top of the script)

**Comment by dingusagar** [comment]
ok thanks ...train_set.py is taking a lot of time to execute...if you could upload the results of the training programs, then we could have directly used them in the raspberry pi

**Comment by raspberian1234** [comment]
what are feature engineering should be done to get vectors
